// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/proto/call.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallStateEnum int32

const (
	CallStateEnum_UNKNOWN    CallStateEnum = 0
	CallStateEnum_INITIATING CallStateEnum = 1
	CallStateEnum_RINGING    CallStateEnum = 2
	CallStateEnum_CONNECTED  CallStateEnum = 3
	CallStateEnum_ENDED      CallStateEnum = 4
)

// Enum value maps for CallStateEnum.
var (
	CallStateEnum_name = map[int32]string{
		0: "UNKNOWN",
		1: "INITIATING",
		2: "RINGING",
		3: "CONNECTED",
		4: "ENDED",
	}
	CallStateEnum_value = map[string]int32{
		"UNKNOWN":    0,
		"INITIATING": 1,
		"RINGING":    2,
		"CONNECTED":  3,
		"ENDED":      4,
	}
)

func (x CallStateEnum) Enum() *CallStateEnum {
	p := new(CallStateEnum)
	*p = x
	return p
}

func (x CallStateEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallStateEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_call_proto_enumTypes[0].Descriptor()
}

func (CallStateEnum) Type() protoreflect.EnumType {
	return &file_pkg_proto_call_proto_enumTypes[0]
}

func (x CallStateEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallStateEnum.Descriptor instead.
func (CallStateEnum) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{0}
}

type InitiateCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToPeerId      string                 `protobuf:"bytes,1,opt,name=to_peer_id,json=toPeerId,proto3" json:"to_peer_id,omitempty"`
	AudioEnabled  bool                   `protobuf:"varint,2,opt,name=audio_enabled,json=audioEnabled,proto3" json:"audio_enabled,omitempty"`
	VideoEnabled  bool                   `protobuf:"varint,3,opt,name=video_enabled,json=videoEnabled,proto3" json:"video_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCallRequest) Reset() {
	*x = InitiateCallRequest{}
	mi := &file_pkg_proto_call_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCallRequest) ProtoMessage() {}

func (x *InitiateCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCallRequest.ProtoReflect.Descriptor instead.
func (*InitiateCallRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateCallRequest) GetToPeerId() string {
	if x != nil {
		return x.ToPeerId
	}
	return ""
}

func (x *InitiateCallRequest) GetAudioEnabled() bool {
	if x != nil {
		return x.AudioEnabled
	}
	return false
}

func (x *InitiateCallRequest) GetVideoEnabled() bool {
	if x != nil {
		return x.VideoEnabled
	}
	return false
}

type InitiateCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	State         *CallState             `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCallResponse) Reset() {
	*x = InitiateCallResponse{}
	mi := &file_pkg_proto_call_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCallResponse) ProtoMessage() {}

func (x *InitiateCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCallResponse.ProtoReflect.Descriptor instead.
func (*InitiateCallResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateCallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *InitiateCallResponse) GetState() *CallState {
	if x != nil {
		return x.State
	}
	return nil
}

type AnswerCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerCallRequest) Reset() {
	*x = AnswerCallRequest{}
	mi := &file_pkg_proto_call_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerCallRequest) ProtoMessage() {}

func (x *AnswerCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerCallRequest.ProtoReflect.Descriptor instead.
func (*AnswerCallRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{2}
}

func (x *AnswerCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *AnswerCallRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type AnswerCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *CallState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerCallResponse) Reset() {
	*x = AnswerCallResponse{}
	mi := &file_pkg_proto_call_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerCallResponse) ProtoMessage() {}

func (x *AnswerCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerCallResponse.ProtoReflect.Descriptor instead.
func (*AnswerCallResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{3}
}

func (x *AnswerCallResponse) GetState() *CallState {
	if x != nil {
		return x.State
	}
	return nil
}

type EndCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallRequest) Reset() {
	*x = EndCallRequest{}
	mi := &file_pkg_proto_call_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallRequest) ProtoMessage() {}

func (x *EndCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallRequest.ProtoReflect.Descriptor instead.
func (*EndCallRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{4}
}

func (x *EndCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type EndCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallResponse) Reset() {
	*x = EndCallResponse{}
	mi := &file_pkg_proto_call_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallResponse) ProtoMessage() {}

func (x *EndCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallResponse.ProtoReflect.Descriptor instead.
func (*EndCallResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{5}
}

func (x *EndCallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SignalingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "offer", "answer", "ice_candidate"
	Sdp           string                 `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Candidate     string                 `protobuf:"bytes,4,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalingMessage) Reset() {
	*x = SignalingMessage{}
	mi := &file_pkg_proto_call_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalingMessage) ProtoMessage() {}

func (x *SignalingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalingMessage.ProtoReflect.Descriptor instead.
func (*SignalingMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{6}
}

func (x *SignalingMessage) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SignalingMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SignalingMessage) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *SignalingMessage) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

type GetCallStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallStateRequest) Reset() {
	*x = GetCallStateRequest{}
	mi := &file_pkg_proto_call_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallStateRequest) ProtoMessage() {}

func (x *GetCallStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallStateRequest.ProtoReflect.Descriptor instead.
func (*GetCallStateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{7}
}

func (x *GetCallStateRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type CallState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	State         CallStateEnum          `protobuf:"varint,2,opt,name=state,proto3,enum=ledabeer.CallStateEnum" json:"state,omitempty"`
	Participants  []string               `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallState) Reset() {
	*x = CallState{}
	mi := &file_pkg_proto_call_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallState) ProtoMessage() {}

func (x *CallState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallState.ProtoReflect.Descriptor instead.
func (*CallState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{8}
}

func (x *CallState) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallState) GetState() CallStateEnum {
	if x != nil {
		return x.State
	}
	return CallStateEnum_UNKNOWN
}

func (x *CallState) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

var File_pkg_proto_call_proto protoreflect.FileDescriptor

const file_pkg_proto_call_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/call.proto\x12\bledabeer\"}\n" +
	"\x13InitiateCallRequest\x12\x1c\n" +
	"\n" +
	"to_peer_id\x18\x01 \x01(\tR\btoPeerId\x12#\n" +
	"\raudio_enabled\x18\x02 \x01(\bR\faudioEnabled\x12#\n" +
	"\rvideo_enabled\x18\x03 \x01(\bR\fvideoEnabled\"Z\n" +
	"\x14InitiateCallResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12)\n" +
	"\x05state\x18\x02 \x01(\v2\x13.ledabeer.CallStateR\x05state\"D\n" +
	"\x11AnswerCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"?\n" +
	"\x12AnswerCallResponse\x12)\n" +
	"\x05state\x18\x01 \x01(\v2\x13.ledabeer.CallStateR\x05state\")\n" +
	"\x0eEndCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\"+\n" +
	"\x0fEndCallResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"o\n" +
	"\x10SignalingMessage\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03sdp\x18\x03 \x01(\tR\x03sdp\x12\x1c\n" +
	"\tcandidate\x18\x04 \x01(\tR\tcandidate\".\n" +
	"\x13GetCallStateRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\"w\n" +
	"\tCallState\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.ledabeer.CallStateEnumR\x05state\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\tR\fparticipants*S\n" +
	"\rCallStateEnum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"INITIATING\x10\x01\x12\v\n" +
	"\aRINGING\x10\x02\x12\r\n" +
	"\tCONNECTED\x10\x03\x12\t\n" +
	"\x05ENDED\x10\x042\xf8\x02\n" +
	"\vCallService\x12M\n" +
	"\fInitiateCall\x12\x1d.ledabeer.InitiateCallRequest\x1a\x1e.ledabeer.InitiateCallResponse\x12G\n" +
	"\n" +
	"AnswerCall\x12\x1b.ledabeer.AnswerCallRequest\x1a\x1c.ledabeer.AnswerCallResponse\x12>\n" +
	"\aEndCall\x12\x18.ledabeer.EndCallRequest\x1a\x19.ledabeer.EndCallResponse\x12M\n" +
	"\x0fStreamSignaling\x12\x1a.ledabeer.SignalingMessage\x1a\x1a.ledabeer.SignalingMessage(\x010\x01\x12B\n" +
	"\fGetCallState\x12\x1d.ledabeer.GetCallStateRequest\x1a\x13.ledabeer.CallStateB\x1cZ\x1aledabeer/backend/pkg/protob\x06proto3"

var (
	file_pkg_proto_call_proto_rawDescOnce sync.Once
	file_pkg_proto_call_proto_rawDescData []byte
)

func file_pkg_proto_call_proto_rawDescGZIP() []byte {
	file_pkg_proto_call_proto_rawDescOnce.Do(func() {
		file_pkg_proto_call_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_call_proto_rawDesc), len(file_pkg_proto_call_proto_rawDesc)))
	})
	return file_pkg_proto_call_proto_rawDescData
}

var file_pkg_proto_call_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_call_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_call_proto_goTypes = []any{
	(CallStateEnum)(0),           // 0: ledabeer.CallStateEnum
	(*InitiateCallRequest)(nil),  // 1: ledabeer.InitiateCallRequest
	(*InitiateCallResponse)(nil), // 2: ledabeer.InitiateCallResponse
	(*AnswerCallRequest)(nil),    // 3: ledabeer.AnswerCallRequest
	(*AnswerCallResponse)(nil),   // 4: ledabeer.AnswerCallResponse
	(*EndCallRequest)(nil),       // 5: ledabeer.EndCallRequest
	(*EndCallResponse)(nil),      // 6: ledabeer.EndCallResponse
	(*SignalingMessage)(nil),     // 7: ledabeer.SignalingMessage
	(*GetCallStateRequest)(nil),  // 8: ledabeer.GetCallStateRequest
	(*CallState)(nil),            // 9: ledabeer.CallState
}
var file_pkg_proto_call_proto_depIdxs = []int32{
	9, // 0: ledabeer.InitiateCallResponse.state:type_name -> ledabeer.CallState
	9, // 1: ledabeer.AnswerCallResponse.state:type_name -> ledabeer.CallState
	0, // 2: ledabeer.CallState.state:type_name -> ledabeer.CallStateEnum
	1, // 3: ledabeer.CallService.InitiateCall:input_type -> ledabeer.InitiateCallRequest
	3, // 4: ledabeer.CallService.AnswerCall:input_type -> ledabeer.AnswerCallRequest
	5, // 5: ledabeer.CallService.EndCall:input_type -> ledabeer.EndCallRequest
	7, // 6: ledabeer.CallService.StreamSignaling:input_type -> ledabeer.SignalingMessage
	8, // 7: ledabeer.CallService.GetCallState:input_type -> ledabeer.GetCallStateRequest
	2, // 8: ledabeer.CallService.InitiateCall:output_type -> ledabeer.InitiateCallResponse
	4, // 9: ledabeer.CallService.AnswerCall:output_type -> ledabeer.AnswerCallResponse
	6, // 10: ledabeer.CallService.EndCall:output_type -> ledabeer.EndCallResponse
	7, // 11: ledabeer.CallService.StreamSignaling:output_type -> ledabeer.SignalingMessage
	9, // 12: ledabeer.CallService.GetCallState:output_type -> ledabeer.CallState
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_call_proto_init() }
func file_pkg_proto_call_proto_init() {
	if File_pkg_proto_call_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_call_proto_rawDesc), len(file_pkg_proto_call_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_call_proto_goTypes,
		DependencyIndexes: file_pkg_proto_call_proto_depIdxs,
		EnumInfos:         file_pkg_proto_call_proto_enumTypes,
		MessageInfos:      file_pkg_proto_call_proto_msgTypes,
	}.Build()
	File_pkg_proto_call_proto = out.File
	file_pkg_proto_call_proto_goTypes = nil
	file_pkg_proto_call_proto_depIdxs = nil
}
