// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pkg/proto/call.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallService_InitiateCall_FullMethodName    = "/ledabeer.CallService/InitiateCall"
	CallService_AnswerCall_FullMethodName      = "/ledabeer.CallService/AnswerCall"
	CallService_EndCall_FullMethodName         = "/ledabeer.CallService/EndCall"
	CallService_StreamSignaling_FullMethodName = "/ledabeer.CallService/StreamSignaling"
	CallService_GetCallState_FullMethodName    = "/ledabeer.CallService/GetCallState"
)

// CallServiceClient is the client API for CallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallServiceClient interface {
	InitiateCall(ctx context.Context, in *InitiateCallRequest, opts ...grpc.CallOption) (*InitiateCallResponse, error)
	AnswerCall(ctx context.Context, in *AnswerCallRequest, opts ...grpc.CallOption) (*AnswerCallResponse, error)
	EndCall(ctx context.Context, in *EndCallRequest, opts ...grpc.CallOption) (*EndCallResponse, error)
	StreamSignaling(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignalingMessage, SignalingMessage], error)
	GetCallState(ctx context.Context, in *GetCallStateRequest, opts ...grpc.CallOption) (*CallState, error)
}

type callServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallServiceClient(cc grpc.ClientConnInterface) CallServiceClient {
	return &callServiceClient{cc}
}

func (c *callServiceClient) InitiateCall(ctx context.Context, in *InitiateCallRequest, opts ...grpc.CallOption) (*InitiateCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateCallResponse)
	err := c.cc.Invoke(ctx, CallService_InitiateCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) AnswerCall(ctx context.Context, in *AnswerCallRequest, opts ...grpc.CallOption) (*AnswerCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerCallResponse)
	err := c.cc.Invoke(ctx, CallService_AnswerCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) EndCall(ctx context.Context, in *EndCallRequest, opts ...grpc.CallOption) (*EndCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndCallResponse)
	err := c.cc.Invoke(ctx, CallService_EndCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) StreamSignaling(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignalingMessage, SignalingMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CallService_ServiceDesc.Streams[0], CallService_StreamSignaling_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SignalingMessage, SignalingMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallService_StreamSignalingClient = grpc.BidiStreamingClient[SignalingMessage, SignalingMessage]

func (c *callServiceClient) GetCallState(ctx context.Context, in *GetCallStateRequest, opts ...grpc.CallOption) (*CallState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallState)
	err := c.cc.Invoke(ctx, CallService_GetCallState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallServiceServer is the server API for CallService service.
// All implementations must embed UnimplementedCallServiceServer
// for forward compatibility.
type CallServiceServer interface {
	InitiateCall(context.Context, *InitiateCallRequest) (*InitiateCallResponse, error)
	AnswerCall(context.Context, *AnswerCallRequest) (*AnswerCallResponse, error)
	EndCall(context.Context, *EndCallRequest) (*EndCallResponse, error)
	StreamSignaling(grpc.BidiStreamingServer[SignalingMessage, SignalingMessage]) error
	GetCallState(context.Context, *GetCallStateRequest) (*CallState, error)
	mustEmbedUnimplementedCallServiceServer()
}

// UnimplementedCallServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallServiceServer struct{}

func (UnimplementedCallServiceServer) InitiateCall(context.Context, *InitiateCallRequest) (*InitiateCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateCall not implemented")
}
func (UnimplementedCallServiceServer) AnswerCall(context.Context, *AnswerCallRequest) (*AnswerCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnswerCall not implemented")
}
func (UnimplementedCallServiceServer) EndCall(context.Context, *EndCallRequest) (*EndCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndCall not implemented")
}
func (UnimplementedCallServiceServer) StreamSignaling(grpc.BidiStreamingServer[SignalingMessage, SignalingMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamSignaling not implemented")
}
func (UnimplementedCallServiceServer) GetCallState(context.Context, *GetCallStateRequest) (*CallState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCallState not implemented")
}
func (UnimplementedCallServiceServer) mustEmbedUnimplementedCallServiceServer() {}
func (UnimplementedCallServiceServer) testEmbeddedByValue()                     {}

// UnsafeCallServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallServiceServer will
// result in compilation errors.
type UnsafeCallServiceServer interface {
	mustEmbedUnimplementedCallServiceServer()
}

func RegisterCallServiceServer(s grpc.ServiceRegistrar, srv CallServiceServer) {
	// If the following call pancis, it indicates UnimplementedCallServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallService_ServiceDesc, srv)
}

func _CallService_InitiateCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).InitiateCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_InitiateCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).InitiateCall(ctx, req.(*InitiateCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_AnswerCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).AnswerCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_AnswerCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).AnswerCall(ctx, req.(*AnswerCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_EndCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).EndCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_EndCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).EndCall(ctx, req.(*EndCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_StreamSignaling_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CallServiceServer).StreamSignaling(&grpc.GenericServerStream[SignalingMessage, SignalingMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallService_StreamSignalingServer = grpc.BidiStreamingServer[SignalingMessage, SignalingMessage]

func _CallService_GetCallState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCallStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).GetCallState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_GetCallState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).GetCallState(ctx, req.(*GetCallStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CallService_ServiceDesc is the grpc.ServiceDesc for CallService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledabeer.CallService",
	HandlerType: (*CallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateCall",
			Handler:    _CallService_InitiateCall_Handler,
		},
		{
			MethodName: "AnswerCall",
			Handler:    _CallService_AnswerCall_Handler,
		},
		{
			MethodName: "EndCall",
			Handler:    _CallService_EndCall_Handler,
		},
		{
			MethodName: "GetCallState",
			Handler:    _CallService_GetCallState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSignaling",
			Handler:       _CallService_StreamSignaling_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/call.proto",
}
