// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pkg/proto/media.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaService_UploadMedia_FullMethodName      = "/ledabeer.MediaService/UploadMedia"
	MediaService_DownloadMedia_FullMethodName    = "/ledabeer.MediaService/DownloadMedia"
	MediaService_GetMediaInfo_FullMethodName     = "/ledabeer.MediaService/GetMediaInfo"
	MediaService_SendMediaMessage_FullMethodName = "/ledabeer.MediaService/SendMediaMessage"
)

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaServiceClient interface {
	UploadMedia(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MediaChunk, UploadMediaResponse], error)
	DownloadMedia(ctx context.Context, in *DownloadMediaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MediaChunk], error)
	GetMediaInfo(ctx context.Context, in *GetMediaInfoRequest, opts ...grpc.CallOption) (*MediaInfo, error)
	SendMediaMessage(ctx context.Context, in *SendMediaMessageRequest, opts ...grpc.CallOption) (*SendMediaMessageResponse, error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) UploadMedia(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MediaChunk, UploadMediaResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaService_ServiceDesc.Streams[0], MediaService_UploadMedia_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MediaChunk, UploadMediaResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaService_UploadMediaClient = grpc.ClientStreamingClient[MediaChunk, UploadMediaResponse]

func (c *mediaServiceClient) DownloadMedia(ctx context.Context, in *DownloadMediaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MediaChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaService_ServiceDesc.Streams[1], MediaService_DownloadMedia_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadMediaRequest, MediaChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaService_DownloadMediaClient = grpc.ServerStreamingClient[MediaChunk]

func (c *mediaServiceClient) GetMediaInfo(ctx context.Context, in *GetMediaInfoRequest, opts ...grpc.CallOption) (*MediaInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MediaInfo)
	err := c.cc.Invoke(ctx, MediaService_GetMediaInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) SendMediaMessage(ctx context.Context, in *SendMediaMessageRequest, opts ...grpc.CallOption) (*SendMediaMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMediaMessageResponse)
	err := c.cc.Invoke(ctx, MediaService_SendMediaMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServiceServer is the server API for MediaService service.
// All implementations must embed UnimplementedMediaServiceServer
// for forward compatibility.
type MediaServiceServer interface {
	UploadMedia(grpc.ClientStreamingServer[MediaChunk, UploadMediaResponse]) error
	DownloadMedia(*DownloadMediaRequest, grpc.ServerStreamingServer[MediaChunk]) error
	GetMediaInfo(context.Context, *GetMediaInfoRequest) (*MediaInfo, error)
	SendMediaMessage(context.Context, *SendMediaMessageRequest) (*SendMediaMessageResponse, error)
	mustEmbedUnimplementedMediaServiceServer()
}

// UnimplementedMediaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaServiceServer struct{}

func (UnimplementedMediaServiceServer) UploadMedia(grpc.ClientStreamingServer[MediaChunk, UploadMediaResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadMedia not implemented")
}
func (UnimplementedMediaServiceServer) DownloadMedia(*DownloadMediaRequest, grpc.ServerStreamingServer[MediaChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadMedia not implemented")
}
func (UnimplementedMediaServiceServer) GetMediaInfo(context.Context, *GetMediaInfoRequest) (*MediaInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaInfo not implemented")
}
func (UnimplementedMediaServiceServer) SendMediaMessage(context.Context, *SendMediaMessageRequest) (*SendMediaMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMediaMessage not implemented")
}
func (UnimplementedMediaServiceServer) mustEmbedUnimplementedMediaServiceServer() {}
func (UnimplementedMediaServiceServer) testEmbeddedByValue()                      {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	// If the following call pancis, it indicates UnimplementedMediaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_UploadMedia_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaServiceServer).UploadMedia(&grpc.GenericServerStream[MediaChunk, UploadMediaResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaService_UploadMediaServer = grpc.ClientStreamingServer[MediaChunk, UploadMediaResponse]

func _MediaService_DownloadMedia_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadMediaRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MediaServiceServer).DownloadMedia(m, &grpc.GenericServerStream[DownloadMediaRequest, MediaChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaService_DownloadMediaServer = grpc.ServerStreamingServer[MediaChunk]

func _MediaService_GetMediaInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetMediaInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetMediaInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetMediaInfo(ctx, req.(*GetMediaInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_SendMediaMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMediaMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).SendMediaMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_SendMediaMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).SendMediaMessage(ctx, req.(*SendMediaMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledabeer.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMediaInfo",
			Handler:    _MediaService_GetMediaInfo_Handler,
		},
		{
			MethodName: "SendMediaMessage",
			Handler:    _MediaService_SendMediaMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadMedia",
			Handler:       _MediaService_UploadMedia_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadMedia",
			Handler:       _MediaService_DownloadMedia_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/proto/media.proto",
}
