// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/proto/media.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMediaInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaInfoRequest) Reset() {
	*x = GetMediaInfoRequest{}
	mi := &file_pkg_proto_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaInfoRequest) ProtoMessage() {}

func (x *GetMediaInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMediaInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{0}
}

func (x *GetMediaInfoRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type MediaChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaChunk) Reset() {
	*x = MediaChunk{}
	mi := &file_pkg_proto_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaChunk) ProtoMessage() {}

func (x *MediaChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaChunk.ProtoReflect.Descriptor instead.
func (*MediaChunk) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{1}
}

func (x *MediaChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MediaChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *MediaChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type UploadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaResponse) Reset() {
	*x = UploadMediaResponse{}
	mi := &file_pkg_proto_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaResponse) ProtoMessage() {}

func (x *UploadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadMediaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{2}
}

func (x *UploadMediaResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *UploadMediaResponse) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *UploadMediaResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DownloadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadMediaRequest) Reset() {
	*x = DownloadMediaRequest{}
	mi := &file_pkg_proto_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMediaRequest) ProtoMessage() {}

func (x *DownloadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMediaRequest.ProtoReflect.Descriptor instead.
func (*DownloadMediaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadMediaRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type MediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaInfo) Reset() {
	*x = MediaInfo{}
	mi := &file_pkg_proto_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaInfo) ProtoMessage() {}

func (x *MediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaInfo.ProtoReflect.Descriptor instead.
func (*MediaInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{4}
}

func (x *MediaInfo) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *MediaInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MediaInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SendMediaMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToPeerId      string                 `protobuf:"bytes,1,opt,name=to_peer_id,json=toPeerId,proto3" json:"to_peer_id,omitempty"`
	MediaCid      string                 `protobuf:"bytes,2,opt,name=media_cid,json=mediaCid,proto3" json:"media_cid,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMediaMessageRequest) Reset() {
	*x = SendMediaMessageRequest{}
	mi := &file_pkg_proto_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMediaMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMediaMessageRequest) ProtoMessage() {}

func (x *SendMediaMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMediaMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMediaMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{5}
}

func (x *SendMediaMessageRequest) GetToPeerId() string {
	if x != nil {
		return x.ToPeerId
	}
	return ""
}

func (x *SendMediaMessageRequest) GetMediaCid() string {
	if x != nil {
		return x.MediaCid
	}
	return ""
}

func (x *SendMediaMessageRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type SendMediaMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMediaMessageResponse) Reset() {
	*x = SendMediaMessageResponse{}
	mi := &file_pkg_proto_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMediaMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMediaMessageResponse) ProtoMessage() {}

func (x *SendMediaMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMediaMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMediaMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{6}
}

func (x *SendMediaMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMediaMessageResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_proto_media_proto protoreflect.FileDescriptor

const file_pkg_proto_media_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/media.proto\x12\bledabeer\"'\n" +
	"\x13GetMediaInfoRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"d\n" +
	"\n" +
	"MediaChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\"V\n" +
	"\x13UploadMediaResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"(\n" +
	"\x14DownloadMediaRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"l\n" +
	"\tMediaInfo\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"q\n" +
	"\x17SendMediaMessageRequest\x12\x1c\n" +
	"\n" +
	"to_peer_id\x18\x01 \x01(\tR\btoPeerId\x12\x1b\n" +
	"\tmedia_cid\x18\x02 \x01(\tR\bmediaCid\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\"W\n" +
	"\x18SendMediaMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\xbc\x02\n" +
	"\fMediaService\x12D\n" +
	"\vUploadMedia\x12\x14.ledabeer.MediaChunk\x1a\x1d.ledabeer.UploadMediaResponse(\x01\x12G\n" +
	"\rDownloadMedia\x12\x1e.ledabeer.DownloadMediaRequest\x1a\x14.ledabeer.MediaChunk0\x01\x12B\n" +
	"\fGetMediaInfo\x12\x1d.ledabeer.GetMediaInfoRequest\x1a\x13.ledabeer.MediaInfo\x12Y\n" +
	"\x10SendMediaMessage\x12!.ledabeer.SendMediaMessageRequest\x1a\".ledabeer.SendMediaMessageResponseB\x1cZ\x1aledabeer/backend/pkg/protob\x06proto3"

var (
	file_pkg_proto_media_proto_rawDescOnce sync.Once
	file_pkg_proto_media_proto_rawDescData []byte
)

func file_pkg_proto_media_proto_rawDescGZIP() []byte {
	file_pkg_proto_media_proto_rawDescOnce.Do(func() {
		file_pkg_proto_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_media_proto_rawDesc), len(file_pkg_proto_media_proto_rawDesc)))
	})
	return file_pkg_proto_media_proto_rawDescData
}

var file_pkg_proto_media_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_media_proto_goTypes = []any{
	(*GetMediaInfoRequest)(nil),      // 0: ledabeer.GetMediaInfoRequest
	(*MediaChunk)(nil),               // 1: ledabeer.MediaChunk
	(*UploadMediaResponse)(nil),      // 2: ledabeer.UploadMediaResponse
	(*DownloadMediaRequest)(nil),     // 3: ledabeer.DownloadMediaRequest
	(*MediaInfo)(nil),                // 4: ledabeer.MediaInfo
	(*SendMediaMessageRequest)(nil),  // 5: ledabeer.SendMediaMessageRequest
	(*SendMediaMessageResponse)(nil), // 6: ledabeer.SendMediaMessageResponse
}
var file_pkg_proto_media_proto_depIdxs = []int32{
	1, // 0: ledabeer.MediaService.UploadMedia:input_type -> ledabeer.MediaChunk
	3, // 1: ledabeer.MediaService.DownloadMedia:input_type -> ledabeer.DownloadMediaRequest
	0, // 2: ledabeer.MediaService.GetMediaInfo:input_type -> ledabeer.GetMediaInfoRequest
	5, // 3: ledabeer.MediaService.SendMediaMessage:input_type -> ledabeer.SendMediaMessageRequest
	2, // 4: ledabeer.MediaService.UploadMedia:output_type -> ledabeer.UploadMediaResponse
	1, // 5: ledabeer.MediaService.DownloadMedia:output_type -> ledabeer.MediaChunk
	4, // 6: ledabeer.MediaService.GetMediaInfo:output_type -> ledabeer.MediaInfo
	6, // 7: ledabeer.MediaService.SendMediaMessage:output_type -> ledabeer.SendMediaMessageResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_media_proto_init() }
func file_pkg_proto_media_proto_init() {
	if File_pkg_proto_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_media_proto_rawDesc), len(file_pkg_proto_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_media_proto_goTypes,
		DependencyIndexes: file_pkg_proto_media_proto_depIdxs,
		MessageInfos:      file_pkg_proto_media_proto_msgTypes,
	}.Build()
	File_pkg_proto_media_proto = out.File
	file_pkg_proto_media_proto_goTypes = nil
	file_pkg_proto_media_proto_depIdxs = nil
}
