// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/proto/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToPeerId      string                 `protobuf:"bytes,1,opt,name=to_peer_id,json=toPeerId,proto3" json:"to_peer_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_pkg_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetToPeerId() string {
	if x != nil {
		return x.ToPeerId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FromPeerId    string                 `protobuf:"bytes,2,opt,name=from_peer_id,json=fromPeerId,proto3" json:"from_peer_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetFromPeerId() string {
	if x != nil {
		return x.FromPeerId
	}
	return ""
}

func (x *Message) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReceiveMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMessagesRequest) Reset() {
	*x = ReceiveMessagesRequest{}
	mi := &file_pkg_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessagesRequest) ProtoMessage() {}

func (x *ReceiveMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessagesRequest.ProtoReflect.Descriptor instead.
func (*ReceiveMessagesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{3}
}

type SendGroupMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMessageRequest) Reset() {
	*x = SendGroupMessageRequest{}
	mi := &file_pkg_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMessageRequest) ProtoMessage() {}

func (x *SendGroupMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMessageRequest.ProtoReflect.Descriptor instead.
func (*SendGroupMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *SendGroupMessageRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SendGroupMessageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetMessageHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageHistoryRequest) Reset() {
	*x = GetMessageHistoryRequest{}
	mi := &file_pkg_proto_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageHistoryRequest) ProtoMessage() {}

func (x *GetMessageHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetMessageHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessageHistoryRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *GetMessageHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MessageHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHistoryResponse) Reset() {
	*x = MessageHistoryResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHistoryResponse) ProtoMessage() {}

func (x *MessageHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHistoryResponse.ProtoReflect.Descriptor instead.
func (*MessageHistoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{6}
}

func (x *MessageHistoryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_pkg_proto_message_proto protoreflect.FileDescriptor

const file_pkg_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/message.proto\x12\bledabeer\"L\n" +
	"\x12SendMessageRequest\x12\x1c\n" +
	"\n" +
	"to_peer_id\x18\x01 \x01(\tR\btoPeerId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"R\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x82\x01\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12 \n" +
	"\ffrom_peer_id\x18\x02 \x01(\tR\n" +
	"fromPeerId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x18\n" +
	"\x16ReceiveMessagesRequest\"N\n" +
	"\x17SendGroupMessageRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"I\n" +
	"\x18GetMessageHistoryRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"G\n" +
	"\x16MessageHistoryResponse\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.ledabeer.MessageR\bmessages2\xd7\x02\n" +
	"\x0eMessageService\x12J\n" +
	"\vSendMessage\x12\x1c.ledabeer.SendMessageRequest\x1a\x1d.ledabeer.SendMessageResponse\x12H\n" +
	"\x0fReceiveMessages\x12 .ledabeer.ReceiveMessagesRequest\x1a\x11.ledabeer.Message0\x01\x12T\n" +
	"\x10SendGroupMessage\x12!.ledabeer.SendGroupMessageRequest\x1a\x1d.ledabeer.SendMessageResponse\x12Y\n" +
	"\x11GetMessageHistory\x12\".ledabeer.GetMessageHistoryRequest\x1a .ledabeer.MessageHistoryResponseB\x1cZ\x1aledabeer/backend/pkg/protob\x06proto3"

var (
	file_pkg_proto_message_proto_rawDescOnce sync.Once
	file_pkg_proto_message_proto_rawDescData []byte
)

func file_pkg_proto_message_proto_rawDescGZIP() []byte {
	file_pkg_proto_message_proto_rawDescOnce.Do(func() {
		file_pkg_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_message_proto_rawDesc), len(file_pkg_proto_message_proto_rawDesc)))
	})
	return file_pkg_proto_message_proto_rawDescData
}

var file_pkg_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_message_proto_goTypes = []any{
	(*SendMessageRequest)(nil),       // 0: ledabeer.SendMessageRequest
	(*SendMessageResponse)(nil),      // 1: ledabeer.SendMessageResponse
	(*Message)(nil),                  // 2: ledabeer.Message
	(*ReceiveMessagesRequest)(nil),   // 3: ledabeer.ReceiveMessagesRequest
	(*SendGroupMessageRequest)(nil),  // 4: ledabeer.SendGroupMessageRequest
	(*GetMessageHistoryRequest)(nil), // 5: ledabeer.GetMessageHistoryRequest
	(*MessageHistoryResponse)(nil),   // 6: ledabeer.MessageHistoryResponse
}
var file_pkg_proto_message_proto_depIdxs = []int32{
	2, // 0: ledabeer.MessageHistoryResponse.messages:type_name -> ledabeer.Message
	0, // 1: ledabeer.MessageService.SendMessage:input_type -> ledabeer.SendMessageRequest
	3, // 2: ledabeer.MessageService.ReceiveMessages:input_type -> ledabeer.ReceiveMessagesRequest
	4, // 3: ledabeer.MessageService.SendGroupMessage:input_type -> ledabeer.SendGroupMessageRequest
	5, // 4: ledabeer.MessageService.GetMessageHistory:input_type -> ledabeer.GetMessageHistoryRequest
	1, // 5: ledabeer.MessageService.SendMessage:output_type -> ledabeer.SendMessageResponse
	2, // 6: ledabeer.MessageService.ReceiveMessages:output_type -> ledabeer.Message
	1, // 7: ledabeer.MessageService.SendGroupMessage:output_type -> ledabeer.SendMessageResponse
	6, // 8: ledabeer.MessageService.GetMessageHistory:output_type -> ledabeer.MessageHistoryResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_message_proto_init() }
func file_pkg_proto_message_proto_init() {
	if File_pkg_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_message_proto_rawDesc), len(file_pkg_proto_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_message_proto_goTypes,
		DependencyIndexes: file_pkg_proto_message_proto_depIdxs,
		MessageInfos:      file_pkg_proto_message_proto_msgTypes,
	}.Build()
	File_pkg_proto_message_proto = out.File
	file_pkg_proto_message_proto_goTypes = nil
	file_pkg_proto_message_proto_depIdxs = nil
}
