// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/proto/peer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersRequest) Reset() {
	*x = GetPeersRequest{}
	mi := &file_pkg_proto_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersRequest) ProtoMessage() {}

func (x *GetPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersRequest.ProtoReflect.Descriptor instead.
func (*GetPeersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_peer_proto_rawDescGZIP(), []int{0}
}

type GetPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	mi := &file_pkg_proto_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_peer_proto_rawDescGZIP(), []int{1}
}

func (x *GetPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GetPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerRequest) Reset() {
	*x = GetPeerRequest{}
	mi := &file_pkg_proto_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerRequest) ProtoMessage() {}

func (x *GetPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerRequest.ProtoReflect.Descriptor instead.
func (*GetPeerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_peer_proto_rawDescGZIP(), []int{2}
}

func (x *GetPeerRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type GetPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *Peer                  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerResponse) Reset() {
	*x = GetPeerResponse{}
	mi := &file_pkg_proto_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerResponse) ProtoMessage() {}

func (x *GetPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerResponse.ProtoReflect.Descriptor instead.
func (*GetPeerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_peer_proto_rawDescGZIP(), []int{3}
}

func (x *GetPeerResponse) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *GetPeerResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetConnectedPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectedPeersRequest) Reset() {
	*x = GetConnectedPeersRequest{}
	mi := &file_pkg_proto_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectedPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectedPeersRequest) ProtoMessage() {}

func (x *GetConnectedPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectedPeersRequest.ProtoReflect.Descriptor instead.
func (*GetConnectedPeersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_peer_proto_rawDescGZIP(), []int{4}
}

type GetConnectedPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectedPeersResponse) Reset() {
	*x = GetConnectedPeersResponse{}
	mi := &file_pkg_proto_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectedPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectedPeersResponse) ProtoMessage() {}

func (x *GetConnectedPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectedPeersResponse.ProtoReflect.Descriptor instead.
func (*GetConnectedPeersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_peer_proto_rawDescGZIP(), []int{5}
}

func (x *GetConnectedPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	LastSeen      int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Addresses     []string               `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_pkg_proto_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_pkg_proto_peer_proto_rawDescGZIP(), []int{6}
}

func (x *Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Peer) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Peer) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *Peer) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_pkg_proto_peer_proto protoreflect.FileDescriptor

const file_pkg_proto_peer_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/peer.proto\x12\bledabeer\"\x11\n" +
	"\x0fGetPeersRequest\"8\n" +
	"\x10GetPeersResponse\x12$\n" +
	"\x05peers\x18\x01 \x03(\v2\x0e.ledabeer.PeerR\x05peers\")\n" +
	"\x0eGetPeerRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"K\n" +
	"\x0fGetPeerResponse\x12\"\n" +
	"\x04peer\x18\x01 \x01(\v2\x0e.ledabeer.PeerR\x04peer\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x1a\n" +
	"\x18GetConnectedPeersRequest\"A\n" +
	"\x19GetConnectedPeersResponse\x12$\n" +
	"\x05peers\x18\x01 \x03(\v2\x0e.ledabeer.PeerR\x05peers\"}\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\x12\x1c\n" +
	"\taddresses\x18\x05 \x03(\tR\taddresses2\xee\x01\n" +
	"\vPeerService\x12A\n" +
	"\bGetPeers\x12\x19.ledabeer.GetPeersRequest\x1a\x1a.ledabeer.GetPeersResponse\x12>\n" +
	"\aGetPeer\x12\x18.ledabeer.GetPeerRequest\x1a\x19.ledabeer.GetPeerResponse\x12\\\n" +
	"\x11GetConnectedPeers\x12\".ledabeer.GetConnectedPeersRequest\x1a#.ledabeer.GetConnectedPeersResponseB\x1cZ\x1aledabeer/backend/pkg/protob\x06proto3"

var (
	file_pkg_proto_peer_proto_rawDescOnce sync.Once
	file_pkg_proto_peer_proto_rawDescData []byte
)

func file_pkg_proto_peer_proto_rawDescGZIP() []byte {
	file_pkg_proto_peer_proto_rawDescOnce.Do(func() {
		file_pkg_proto_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_peer_proto_rawDesc), len(file_pkg_proto_peer_proto_rawDesc)))
	})
	return file_pkg_proto_peer_proto_rawDescData
}

var file_pkg_proto_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_peer_proto_goTypes = []any{
	(*GetPeersRequest)(nil),           // 0: ledabeer.GetPeersRequest
	(*GetPeersResponse)(nil),          // 1: ledabeer.GetPeersResponse
	(*GetPeerRequest)(nil),            // 2: ledabeer.GetPeerRequest
	(*GetPeerResponse)(nil),           // 3: ledabeer.GetPeerResponse
	(*GetConnectedPeersRequest)(nil),  // 4: ledabeer.GetConnectedPeersRequest
	(*GetConnectedPeersResponse)(nil), // 5: ledabeer.GetConnectedPeersResponse
	(*Peer)(nil),                      // 6: ledabeer.Peer
}
var file_pkg_proto_peer_proto_depIdxs = []int32{
	6, // 0: ledabeer.GetPeersResponse.peers:type_name -> ledabeer.Peer
	6, // 1: ledabeer.GetPeerResponse.peer:type_name -> ledabeer.Peer
	6, // 2: ledabeer.GetConnectedPeersResponse.peers:type_name -> ledabeer.Peer
	0, // 3: ledabeer.PeerService.GetPeers:input_type -> ledabeer.GetPeersRequest
	2, // 4: ledabeer.PeerService.GetPeer:input_type -> ledabeer.GetPeerRequest
	4, // 5: ledabeer.PeerService.GetConnectedPeers:input_type -> ledabeer.GetConnectedPeersRequest
	1, // 6: ledabeer.PeerService.GetPeers:output_type -> ledabeer.GetPeersResponse
	3, // 7: ledabeer.PeerService.GetPeer:output_type -> ledabeer.GetPeerResponse
	5, // 8: ledabeer.PeerService.GetConnectedPeers:output_type -> ledabeer.GetConnectedPeersResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_peer_proto_init() }
func file_pkg_proto_peer_proto_init() {
	if File_pkg_proto_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_peer_proto_rawDesc), len(file_pkg_proto_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_peer_proto_goTypes,
		DependencyIndexes: file_pkg_proto_peer_proto_depIdxs,
		MessageInfos:      file_pkg_proto_peer_proto_msgTypes,
	}.Build()
	File_pkg_proto_peer_proto = out.File
	file_pkg_proto_peer_proto_goTypes = nil
	file_pkg_proto_peer_proto_depIdxs = nil
}
